# -*- coding: utf-8 -*-
"""
/***************************************************************************
 pyNKE
                                 A QGIS plugin
 This plugin manage data fo an NKE sensor
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-04-14
        copyright            : (C) 2024 by Emmanuel Poizot
        email                : emmanuel.poizot@lecnam.net
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load pyNKE class from file pyNKE.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .nke_sensor import pyNKE
    return pyNKE(iface)
